name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

  docker:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t testing-practice .
      - name: Deploy container
        run: |
               docker stop testing-practice || true
               docker rm testing-practice || true

               docker run -d \
                --name testing-practice \
                --restart unless-stopped \
                 --env-file ~/practice-deployment.env \
                 -p 127.0.0.1:5000:5000 \
                  testing-practice:latest
